[2021-08-13 08:45:16,849] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T08:45:15.225892+00:00 [queued]>
[2021-08-13 08:45:16,869] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T08:45:15.225892+00:00 [queued]>
[2021-08-13 08:45:16,870] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-13 08:45:16,870] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-13 08:45:16,870] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-13 08:45:16,883] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_data> on 2021-08-13T08:45:15.225892+00:00
[2021-08-13 08:45:16,888] {standard_task_runner.py:52} INFO - Started process 6474 to run task
[2021-08-13 08:45:16,892] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pipeline_try', 'transform_data', '2021-08-13T08:45:15.225892+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_try1.py', '--cfg-path', '/tmp/tmpzcjmrs74', '--error-file', '/tmp/tmpf01bsloa']
[2021-08-13 08:45:16,899] {standard_task_runner.py:77} INFO - Job 149: Subtask transform_data
[2021-08-13 08:45:16,955] {logging_mixin.py:104} INFO - Running <TaskInstance: pipeline_try.transform_data 2021-08-13T08:45:15.225892+00:00 [running]> on host 99300daf4d26
[2021-08-13 08:45:17,091] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ameysonje242000@gmail.com
AIRFLOW_CTX_DAG_OWNER=amey
AIRFLOW_CTX_DAG_ID=pipeline_try
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2021-08-13T08:45:15.225892+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-13T08:45:15.225892+00:00
[2021-08-13 08:45:17,093] {logging_mixin.py:104} INFO - /opt/data/csv_data.csv
[2021-08-13 08:45:17,093] {logging_mixin.py:104} INFO - /opt/data/csv_data_transformed.csv
[2021-08-13 08:45:17,423] {python.py:151} INFO - Done. Returned value was: None
[2021-08-13 08:45:17,436] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=pipeline_try, task_id=transform_data, execution_date=20210813T084515, start_date=20210813T084516, end_date=20210813T084517
[2021-08-13 08:45:17,471] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-13 08:45:17,508] {local_task_job.py:149} INFO - Task exited with return code 0
