[2021-08-13 09:29:44,972] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T09:21:33.871792+00:00 [queued]>
[2021-08-13 09:29:45,076] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T09:21:33.871792+00:00 [queued]>
[2021-08-13 09:29:45,077] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-13 09:29:45,081] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2021-08-13 09:29:45,083] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-13 09:29:45,121] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_data> on 2021-08-13T09:21:33.871792+00:00
[2021-08-13 09:29:45,157] {standard_task_runner.py:52} INFO - Started process 22492 to run task
[2021-08-13 09:29:45,184] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pipeline_try', 'transform_data', '2021-08-13T09:21:33.871792+00:00', '--job-id', '178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_try1.py', '--cfg-path', '/tmp/tmpf6ztqoq1', '--error-file', '/tmp/tmptsm_s13k']
[2021-08-13 09:29:45,200] {standard_task_runner.py:77} INFO - Job 178: Subtask transform_data
[2021-08-13 09:29:45,630] {logging_mixin.py:104} INFO - Running <TaskInstance: pipeline_try.transform_data 2021-08-13T09:21:33.871792+00:00 [running]> on host 99300daf4d26
[2021-08-13 09:29:45,993] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ameysonje242000@gmail.com
AIRFLOW_CTX_DAG_OWNER=amey
AIRFLOW_CTX_DAG_ID=pipeline_try
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2021-08-13T09:21:33.871792+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-13T09:21:33.871792+00:00
[2021-08-13 09:29:46,017] {logging_mixin.py:104} INFO - /opt/data/csv_data.csv
[2021-08-13 09:29:46,018] {logging_mixin.py:104} INFO - /opt/data/csv_data_transformed.csv
[2021-08-13 09:29:47,725] {python.py:151} INFO - Done. Returned value was: None
[2021-08-13 09:29:47,811] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=pipeline_try, task_id=transform_data, execution_date=20210813T092133, start_date=20210813T092944, end_date=20210813T092947
[2021-08-13 09:29:48,150] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-13 09:29:48,208] {local_task_job.py:149} INFO - Task exited with return code 0
