[2021-08-13 08:43:22,509] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T08:43:20.342682+00:00 [queued]>
[2021-08-13 08:43:22,524] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T08:43:20.342682+00:00 [queued]>
[2021-08-13 08:43:22,525] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-13 08:43:22,526] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-13 08:43:22,526] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-13 08:43:22,535] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_data> on 2021-08-13T08:43:20.342682+00:00
[2021-08-13 08:43:22,539] {standard_task_runner.py:52} INFO - Started process 5668 to run task
[2021-08-13 08:43:22,543] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pipeline_try', 'transform_data', '2021-08-13T08:43:20.342682+00:00', '--job-id', '142', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_try1.py', '--cfg-path', '/tmp/tmpbe5d8hea', '--error-file', '/tmp/tmp4yd0bxrk']
[2021-08-13 08:43:22,549] {standard_task_runner.py:77} INFO - Job 142: Subtask transform_data
[2021-08-13 08:43:22,592] {logging_mixin.py:104} INFO - Running <TaskInstance: pipeline_try.transform_data 2021-08-13T08:43:20.342682+00:00 [running]> on host 99300daf4d26
[2021-08-13 08:43:22,644] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ameysonje242000@gmail.com
AIRFLOW_CTX_DAG_OWNER=amey
AIRFLOW_CTX_DAG_ID=pipeline_try
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2021-08-13T08:43:20.342682+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-13T08:43:20.342682+00:00
[2021-08-13 08:43:22,646] {logging_mixin.py:104} INFO - /opt/data/csv_data.csv
[2021-08-13 08:43:22,646] {logging_mixin.py:104} INFO - /opt/data/csv_data_transformed.csv
[2021-08-13 08:43:22,997] {python.py:151} INFO - Done. Returned value was: None
[2021-08-13 08:43:23,010] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=pipeline_try, task_id=transform_data, execution_date=20210813T084320, start_date=20210813T084322, end_date=20210813T084323
[2021-08-13 08:43:23,042] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-13 08:43:23,076] {local_task_job.py:149} INFO - Task exited with return code 0
