[2021-08-12 08:55:45,961] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.thursday_Task 2021-08-12T08:55:38.356461+00:00 [queued]>
[2021-08-12 08:55:46,045] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.thursday_Task 2021-08-12T08:55:38.356461+00:00 [queued]>
[2021-08-12 08:55:46,046] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 08:55:46,046] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-12 08:55:46,047] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-12 08:55:46,064] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): thursday_Task> on 2021-08-12T08:55:38.356461+00:00
[2021-08-12 08:55:46,073] {standard_task_runner.py:52} INFO - Started process 14519 to run task
[2021-08-12 08:55:46,078] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pipeline_try', 'thursday_Task', '2021-08-12T08:55:38.356461+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_try1.py', '--cfg-path', '/tmp/tmptt1je6q1', '--error-file', '/tmp/tmpwv2hofun']
[2021-08-12 08:55:46,083] {standard_task_runner.py:77} INFO - Job 35: Subtask thursday_Task
[2021-08-12 08:55:46,148] {logging_mixin.py:104} INFO - Running <TaskInstance: pipeline_try.thursday_Task 2021-08-12T08:55:38.356461+00:00 [running]> on host 99300daf4d26
[2021-08-12 08:55:46,224] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ameysonje242000@gmail.com
AIRFLOW_CTX_DAG_OWNER=amey
AIRFLOW_CTX_DAG_ID=pipeline_try
AIRFLOW_CTX_TASK_ID=thursday_Task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-12T08:55:38.356461+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-12T08:55:38.356461+00:00
[2021-08-12 08:55:46,226] {logging_mixin.py:104} INFO - From thursday_Task, so its thursday today
[2021-08-12 08:55:46,227] {python.py:151} INFO - Done. Returned value was: None
[2021-08-12 08:55:46,242] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=pipeline_try, task_id=thursday_Task, execution_date=20210812T085538, start_date=20210812T085545, end_date=20210812T085546
[2021-08-12 08:55:46,290] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-12 08:55:46,332] {local_task_job.py:149} INFO - Task exited with return code 0
