[2021-08-14 05:22:05,322] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T00:00:00+00:00 [queued]>
[2021-08-14 05:22:05,390] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: pipeline_try.transform_data 2021-08-13T00:00:00+00:00 [queued]>
[2021-08-14 05:22:05,394] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-14 05:22:05,394] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-08-14 05:22:05,395] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-14 05:22:05,440] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_data> on 2021-08-13T00:00:00+00:00
[2021-08-14 05:22:05,452] {standard_task_runner.py:52} INFO - Started process 32433 to run task
[2021-08-14 05:22:05,463] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pipeline_try', 'transform_data', '2021-08-13T00:00:00+00:00', '--job-id', '185', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_try1.py', '--cfg-path', '/tmp/tmpayoy474y', '--error-file', '/tmp/tmpwvu41xsd']
[2021-08-14 05:22:05,481] {standard_task_runner.py:77} INFO - Job 185: Subtask transform_data
[2021-08-14 05:22:05,705] {logging_mixin.py:104} INFO - Running <TaskInstance: pipeline_try.transform_data 2021-08-13T00:00:00+00:00 [running]> on host 99300daf4d26
[2021-08-14 05:22:05,947] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ameysonje242000@gmail.com
AIRFLOW_CTX_DAG_OWNER=amey
AIRFLOW_CTX_DAG_ID=pipeline_try
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2021-08-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-13T00:00:00+00:00
[2021-08-14 05:22:05,965] {logging_mixin.py:104} INFO - /opt/data/csv_data.csv
[2021-08-14 05:22:05,980] {logging_mixin.py:104} INFO - /opt/data/csv_data_transformed.csv
[2021-08-14 05:22:07,402] {python.py:151} INFO - Done. Returned value was: None
[2021-08-14 05:22:07,430] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=pipeline_try, task_id=transform_data, execution_date=20210813T000000, start_date=20210814T052205, end_date=20210814T052207
[2021-08-14 05:22:07,544] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-14 05:22:07,573] {local_task_job.py:149} INFO - Task exited with return code 0
